[2025-06-17T15:57:19.795+0200] {processor.py:161} INFO - Started process (PID=240389) to work on /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T15:57:19.796+0200] {processor.py:830} INFO - Processing file /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-17T15:57:19.796+0200] {logging_mixin.py:188} INFO - [2025-06-17T15:57:19.796+0200] {dagbag.py:545} INFO - Filling up the DagBag from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T15:57:19.798+0200] {logging_mixin.py:188} INFO - [2025-06-17T15:57:19.798+0200] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-17T15:57:19.798+0200] {logging_mixin.py:188} INFO - [2025-06-17T15:57:19.798+0200] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-17T15:57:19.798+0200] {processor.py:842} WARNING - No viable dags retrieved from /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T15:57:19.804+0200] {processor.py:183} INFO - Processing /home/florent/Programs/anaconda3/envs/airflow_etl/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
